services:
  rule-engine:
    build: ./rule_engine
    ports:
      - "8000:8000"
    env_file:
      - .env

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - rule-engine
    env_file:
      - .env  
